# aggressive_reset: {reset_distance: 1.84}
base_global_planner: navfn/NavfnROS
base_local_planner: potbot_nav/PotbotLocalPlanner
# clearing_rotation_allowed: true
# conservative_reset: {reset_distance: 3.0}
# conservative_reset_dist: 3.0
controller_frequency: 10.0
controller_patience: 15.0
base_local_planner: potbot_nav/PotbotLocalPlanner

PotbotLocalPlanner:

  recover_distance: 0.01
  stop_margin: 0.1

  # 経路追従コントローラー
  controller_name: potbot_nav/OPF
  controller: 
    optimization_method: all_search

    max_linear_velocity: 0.2
    min_linear_velocity: -0.2
    linear_velocity_increment: 0.05
    
    max_angular_velocity: 1.5
    min_angular_velocity: -1.5
    angular_velocity_increment: 0.1

    max_iteration: 100
    learning_rate: 0.01
    
    stop_margin_angle: 0.1
    stop_margin_distance: 0.1
    time_end: 1.0
    time_increment: 0.2
  
  # ポテンシャル法経路計画
  path_planner_name: potbot_nav/APF
  path_planner:
    apf: 
      distance_threshold_repulsion_field: 0.5
      potential_field_cols: 125
      potential_field_resolution: 0.05
      potential_field_rows: 120
      weight_attraction_field: 0.1
      weight_repulsion_field: 0.1

    apfpp:
      max_path_length: 6.0
      path_search_range: 1
      weight_angle: 0.2
      weight_potential_field: 1.0
    
  # ゴール近傍PIDコントローラー
  recover:
    gain_p: 1.0
    gain_i: 0.1
    gain_d: 0.001
    
    max_linear_velocity: 0.2
    min_linear_velocity: -0.2
    max_angular_velocity: 1.5
    min_angular_velocity: -1.5
    
    stop_margin_angle: 0.1
    stop_margin_distance: 0.1
